const ALL_CATEGORIES = [
	"Breakfast",
	"Brunch",
	"Lunch",
	"Dinner",
	"Pancakes",
	"Sandwiches, Wraps and Rolls",
	"Appetisers",
	"Soups",
	"Salads",
	"Sides",
	"Snacks",
	"Burgers",
	"Pizza",
	"Pies",
	"Quiches and Savoury Tarts",
	"Mince",
	"Lamb",
	"Chicken",
	"Seafood",
	"Rice",
	"Noodles",
	"Pasta",
	"Sausages",
	"Beef",
	"Stir Fry",
	"Pork",
	"Turkey",
	"Duck",
	"Condiments and Spreads",
	"Sauces",
	"Bread",
	"Slices",
	"Muffins, Scones and Scrolls",
	"Biscuits and Cookies",
	"Treats",
	"Baking",
	"Desserts",
	"Cheesecakes",
	"Ice Cream",
	"Smoothies and Shakes",
	"Drinks and Cocktails",
	"Vegetarian",
	"Poultry",
	"Meat",
];

export default async function () {
	return <>{JSON.stringify(ALL_CATEGORIES)}</>;
}
